# SHUNYA lockscreen

background {
    monitor =
    color = rgba(1e1e26ff)
}

label {
    monitor =
    text = $TIME
    font_family = Noto Sans
    font_size = 64
    color = rgba(e6e3edff)
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 56
    outline_thickness = 2
    outer_color = rgba(ffb2beff)
    inner_color = rgba(282832ff)
    font_color = rgba(e6e3edff)
    font_family = Noto Sans
    placeholder_text = Password
    fade_on_empty = false
    rounding = 8
    position = 0, -30
    halign = center
    valign = center
}
