hl.on("hyprland.start", function()
    hl.exec_cmd(os.getenv("HOME") .. "/.config/bin/shunya-theme apply")

    hl.exec_cmd("kdeconnect-indicator")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("quickshell -c shunya-bar")
    hl.exec_cmd("quickshell -c shunya-notifications")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
end)
